### ISSUE TITLE
Make tabs look more like tabs, show active selection

### ISSUE THREAD

**Issue by msporny** [w3c/respec-vc#1]
The current display (shown below) doesn't show you which tab is currently activated. Make it prettier.

![image](https://user-images.githubusercontent.com/108611/141372862-d08259f4-5d78-4959-b8f6-7a596ed098ce.png)

**Comment by kdenhartog** [comment]
When I was originally thinking about this problem I was planning on using the stuff that json-ld-syntax V1.1 already has in it to try and make this work. 

Maybe something in here might be the answer to make this work: https://github.com/w3c/json-ld-syntax/blob/main/index.html#L131-L281

**Comment by BigBlueHat** [comment]
@msporny this looks fixed as of #7 being merged:
![image](https://github.com/w3c/respec-vc/assets/43209/3566e088-ac8b-4e84-a664-b552381a2c21)

**Comment by msporny** [comment]
Newest look is here:

![image](https://github.com/w3c/respec-vc/assets/108611/861fb55e-aa87-450a-b30a-1444d707f8ba)
