### ISSUE TITLE
Add missing cryptosuites

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/respec-vc#15]
* [ ] ecdsa-rdfc-2019
* [x] ecdsa-sd-2023
* [x] eddsa-rdfc-2022
* [ ] bbs-2023

**Comment by BigBlueHat** [comment]
This is going to get crowded...
![image](https://github.com/w3c/respec-vc/assets/43209/339fdcd4-18eb-407f-b86f-19dea18d792e)

@msporny any preference here? I've got at least 3 more to add...not to mention SD-JWT, etc.

**Comment by BigBlueHat** [comment]
Adding `ecdsa-sd-2023` (at least base proof) in #20.

**Comment by msporny** [comment]
> @msporny any preference here? I've got at least 3 more to add...not to mention SD-JWT, etc.

What about this:

* Credential
* ecdsa
* ecdsa-sd
* eddsa
* vc-jose
* vc-cose
* cbor-ld

The let abbr/mouse-over show the following:

* Credential -> "Unsecured credential"
* ecdsa -> "Secured with Data Integrity - ecdsa-rdfc-2019"

... and so on?

**Comment by msporny** [comment]
This was fixed in PR #26, closing.
