### ISSUE TITLE
Failed to attach proof if custom @context included

### ISSUE THREAD

**Issue by amiller-ims** [w3c/respec-vc#2]
When "https://imsglobal.github.io/openbadges-specification/context.json" is included in the list of contexts, the proof cannot be generated. The error is:

> Failed to attach proof to Verifiable Credential. jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.

The URL is public (no CORS) and does return JSON. Do I need a custom documentLoader?

This works,

```
          {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "id": "http://example.edu/credentials/3732",
            "type": ["VerifiableCredential", "OpenBadge"],
            "issuer": {
              "id": "https://example.edu/issuers/565049",
              "type": "IssuerProfile",
              "name": "Example University"
            },
            "issuanceDate": "2010-01-01T00:00:00Z",
            "credentialSubject": {
              "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
            }
          }
```

But this does not,

```
          {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1",
              "https://imsglobal.github.io/openbadges-specification/context.json"
            ],
            "id": "http://example.edu/credentials/3732",
            "type": ["VerifiableCredential", "OpenBadge"],
            "issuer": {
              "id": "https://example.edu/issuers/565049",
              "type": "IssuerProfile",
              "name": "Example University"
            },
            "issuanceDate": "2010-01-01T00:00:00Z",
            "credentialSubject": {
              "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
            }
          }
```

**Comment by davidlehn** [comment]
Yeah, it doesn't look like current documentLoader will load arbitrary contexts.  I don't know what the plan was here, but this seems like a needed feature.  It should probably have two optional easy to use features.  One to enabled fetching local or CORS enabled resources.  Another to add some control to remap URLs.  That would allow you to switch loading remote resources to known local ones in the same hosted directory.  Need to consider network fetching so as not to potentially cause too many requests to context servers.

Also of note is that https://github.com/digitalbazaar/vc-js, jsonld-signatures, and jsonld.js still need some work to detect all potential data issues.  It looks like "OpenBadge" is not defined, and it will be silently dropped.  (This is an issue for 'AlumniCredential' too, see https://github.com/digitalbazaar/vc-js/pull/111.)
