### ISSUE TITLE
Make sure credentialStatus and credentialSchema are not selectively disclosable in SD-JWT examples

### ISSUE THREAD

**Issue by thereisnogabe** [w3c/respec-vc#41]
Related to https://github.com/w3c/vc-jose-cose/issues/285 and https://github.com/w3c/vc-jose-cose/pull/288

**Comment by TallTed** [comment]
Please change issue title from `not disclosable` to `not selectively disclosable`.

**Comment by thereisnogabe** [comment]
Similarly add protections for `@context`, `type`, and `relatedResource` values.

**Comment by thereisnogabe** [comment]
the editors of this spec discusses this should not be in the rendering plugin, but instead an option at a higher layer for implementers of the spec.
