### ISSUE TITLE
Incorporate VC-JOSE-COSE 

### ISSUE THREAD

**Issue by thereisnogabe** [w3c/respec-vc#9]
Related to https://github.com/w3c/vc-jose-cose/issues/214, without support for [VC-JOSE-COSE](https://github.com/w3c/vc-jose-cose) (specifically SD-JWT in this case) it will be difficult to render examples for published VC-JOSE-COSE specs as a part of the W3C process.

It looks like there is already work done here https://github.com/transmute-industries/respec-vc-jwt which could be incorporated into this repo. Unfortunately my JS skills are limited so I am hesitant to open a change request myself.

Is there a maintainer of the project I can work with to see this through?

**Comment by OR13** [comment]
I am willing to do the work to update the code in this repo (which I see is now controlled by the W3C github organization).

I would preserve the current tab UI for "JWT".

I hear that the working group has agreed to secure vc+ld+json with +jwt.

I would add support for +sd-jwt and +cose.

I would use CBOR EDN (diag) for the cose form.

I would add support for VC and VP.

I would add support for selective disclosure.

There would be 5 tabs for vc:

- VerifiableCredential
- DataIntegrityProof
- JWT
- SD-JWT
- COSE

There would be 5 tabs for vp:

- VerifiablePresentation
- DataIntegrityProof
- JWT
- SD-JWT
- COSE

The working group can argue over the ordering, and if it shows bias.

**Comment by David-Chadwick** [comment]
I do not see why there should be a DataIntegrityProof in the JOSE spec, since there are already two CRs that have DataIntegrityProofs in them. Rather, I would prefer to see more tabs to describe the SD-JWT encodings. Specifically, in a previous draft we had the following SD-JWT tabs
Committed
Issued
Disclosed
Presented
and Verified
Whilst not all of these are needed, it would be valuable to have SD-JWT Committed, SD-JWT-Issued and SD-JWT-Presented tabs in the examples

**Comment by thereisnogabe** [comment]
@David-Chadwick are those tabs not present already? https://w3c.github.io/vc-jose-cose/#credentials

**Comment by David-Chadwick** [comment]
Interestingly not when you preview the PRs e.g. see
https://pr-preview.s3.amazonaws.com/w3c/vc-jose-cose/pull/225.html
Thus if one is to accept the PR one is doing it without seeing what the examples actually (or supposedly) look like.
There seems to be something wrong in previewing the PRs if they are not displaying the examples correctly.

**Comment by thereisnogabe** [comment]
@David-Chadwick this issue is opened to fix exactly the problem you're describing
